name: learnable-matern
channels:
  - nvidia
  - pytorch
dependencies:
  - pip
  - python=3.9.19
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - torchvision=0.15.2
  - pip:
    - cupy==12.2.0
    - point-cloud-utils==0.30.4
    - pykdtree==1.3.12
    - python-pycg==0.9.1 -f https://pycg.huangjh.tech/packages/index.html
    - pyyaml==6.0.1
    - scikit-image==0.22.0
    - torch-scatter -f https://data.pyg.org/whl/torch-2.0.1+cu117.html
    - tqdm==4.66.1
    - wandb==0.16.1