module: 'nkf'

model:
   feature_field:
      num_features: 32
      encoder: !include encoder/default_grid_encoder.yaml
      decoder: !include decoder/default_grid_decoder.yaml

   kernel:
      type: 'matern'
      reg_weight: 1.0e-7
      input_type: 'concat' # Options: 'concat', 'only_points', 'only_features'.
      kwargs: {
         'order': '1/2', # Options: '1/2', '3/2', '5/2', 'inf'.
         'h': 1.0
      }
   
   weight_model:
      type: 'none' # or 'simple'.
      hidden_dim: 32
      n_blocks: 5

data:
   dataset: 'shapenet'
   dataset_root: '../data/ShapeNet/'
   num_observations: 1000  
   num_freespace_points: 10_000
   num_surface_points: 5000
   observation_noise: 0.0

train:
   batch_size: 8
   epochs_til_evaluation: 2
   num_workers: 4

eval:
   chunk_size: 100_000
   voxel_resolution: 128
   num_eval_points: 100_000

loss:
   objectives: ['freespace_loss', 'surface_loss']
   weights: [1.0, 0.01]

optimizer:
   method: 'adam'
   lr: 1.0e-4
   optimizer_kwargs: {
      'betas': [0.9, 0.999]
   }

misc:
   accumulate_grad: False
   cond_threshold: 1.0e+5
   surf_eps: 0.005 
   manual_seed: 41